name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up to Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2
      
      - name: Test
        run: make test


